/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 * Generated by MATLAB(R) 9.0 and the Signal Processing Toolbox 7.2.
 * Generated on: 13-Dec-2016 02:34:56
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form II, Second-Order Sections
 * Number of Sections  : 7
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/* 
 * Expected path to tmwtypes.h 
 * C:\Program Files\MATLAB\R2016a\extern\include\tmwtypes.h 
 */
#define MWSPT_NSEC 15
const int NL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,2,1 };
const real64_T NUM[MWSPT_NSEC][3] = {
  {
     0.4438209403556,                 0,                 0 
  },
  {
                   1,   -1.830079315254,                 1 
  },
  {
     0.7132159695562,                 0,                 0 
  },
  {
                   1,    -1.82014653391,                 1 
  },
  {
     0.5633210511649,                 0,                 0 
  },
  {
                   1,   -1.793968089464,                 1 
  },
  {
     0.3579152031787,                 0,                 0 
  },
  {
                   1,   -1.730477624574,                 1 
  },
  {
     0.1566615371476,                 0,                 0 
  },
  {
                   1,   -1.550636697482,                 1 
  },
  {
      0.037861763579,                 0,                 0 
  },
  {
                   1,  -0.8064350498517,                 1 
  },
  {
     0.1651214823228,                 0,                 0 
  },
  {
                   1,                 1,                 0 
  },
  {
                   1,                 0,                 0 
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,3,1,3,1,3,1,3,1,3,1,2,1 };
const real64_T DEN[MWSPT_NSEC][3] = {
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.852151912377,   0.9867438665131 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.828109941591,   0.9563843057862 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.797745515994,   0.9138076284103 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.755690811767,   0.8521569675286 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.702440107177,   0.7728380528876 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,   -1.651800090424,   0.6969905643826 
  },
  {
                   1,                 0,                 0 
  },
  {
                   1,  -0.8149587666495,                 0 
  },
  {
                   1,                 0,                 0 
  }
};
